export default [
  {
    login: "kaxiii",
    id: 15610911,
    node_id: "MDQ6VXNlcjE1NjEwOTEx",
    avatar_url: "https://avatars.githubusercontent.com/u/15610911?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/kaxiii",
    html_url: "https://github.com/kaxiii",
    followers_url: "https://api.github.com/users/kaxiii/followers",
    following_url: "https://api.github.com/users/kaxiii/following{/other_user}",
    gists_url: "https://api.github.com/users/kaxiii/gists{/gist_id}",
    starred_url: "https://api.github.com/users/kaxiii/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/kaxiii/subscriptions",
    organizations_url: "https://api.github.com/users/kaxiii/orgs",
    repos_url: "https://api.github.com/users/kaxiii/repos",
    events_url: "https://api.github.com/users/kaxiii/events{/privacy}",
    received_events_url: "https://api.github.com/users/kaxiii/received_events",
    type: "User",
    site_admin: false
  },
  {
    login: "Giorgi-Jalali",
    id: 91850260,
    node_id: "U_kgDOBXmGFA",
    avatar_url: "https://avatars.githubusercontent.com/u/91850260?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Giorgi-Jalali",
    html_url: "https://github.com/Giorgi-Jalali",
    followers_url: "https://api.github.com/users/Giorgi-Jalali/followers",
    following_url: "https://api.github.com/users/Giorgi-Jalali/following{/other_user}",
    gists_url: "https://api.github.com/users/Giorgi-Jalali/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Giorgi-Jalali/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Giorgi-Jalali/subscriptions",
    organizations_url: "https://api.github.com/users/Giorgi-Jalali/orgs",
    repos_url: "https://api.github.com/users/Giorgi-Jalali/repos",
    events_url: "https://api.github.com/users/Giorgi-Jalali/events{/privacy}",
    received_events_url: "https://api.github.com/users/Giorgi-Jalali/received_events",
    type: "User",
    site_admin: false
  },
  {
    login: "Lay0us1",
    id: 99304369,
    node_id: "U_kgDOBetDsQ",
    avatar_url: "https://avatars.githubusercontent.com/u/99304369?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Lay0us1",
    html_url: "https://github.com/Lay0us1",
    followers_url: "https://api.github.com/users/Lay0us1/followers",
    following_url: "https://api.github.com/users/Lay0us1/following{/other_user}",
    gists_url: "https://api.github.com/users/Lay0us1/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Lay0us1/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Lay0us1/subscriptions",
    organizations_url: "https://api.github.com/users/Lay0us1/orgs",
    repos_url: "https://api.github.com/users/Lay0us1/repos",
    events_url: "https://api.github.com/users/Lay0us1/events{/privacy}",
    received_events_url: "https://api.github.com/users/Lay0us1/received_events",
    type: "User",
    site_admin: false
  }
]