export default {
  login: 'ekizashvilit',
  id: 98412366,
  node_id: 'U_kgDOBd2nTg',
  avatar_url: 'https://avatars.githubusercontent.com/u/98412366?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/ekizashvilit',
  html_url: 'https://github.com/ekizashvilit',
  followers_url: 'https://api.github.com/users/ekizashvilit/followers',
  following_url:
    'https://api.github.com/users/ekizashvilit/following{/other_user}',
  gists_url: 'https://api.github.com/users/ekizashvilit/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/ekizashvilit/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/ekizashvilit/subscriptions',
  organizations_url: 'https://api.github.com/users/ekizashvilit/orgs',
  repos_url: 'https://api.github.com/users/ekizashvilit/repos',
  events_url: 'https://api.github.com/users/ekizashvilit/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/ekizashvilit/received_events',
  type: 'User',
  site_admin: false,
  name: 'Teona Ekizashvili',
  company: null,
  blog: '',
  location: 'Tbilisi, Georgia',
  email: null,
  hireable: null,
  bio: 'Full Stack Developer',
  twitter_username: 'ekizashvilit',
  public_repos: 19,
  public_gists: 1,
  followers: 3,
  following: 1,
  created_at: '2022-01-25T16:14:13Z',
  updated_at: '2023-02-19T11:26:03Z',
};
